# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bs_tree <- function(y) {
    .Call('_NPT_bs_tree', PACKAGE = 'NPT', y)
}

num_sum <- function(eta, y, u, v, TREE) {
    .Call('_NPT_num_sum', PACKAGE = 'NPT', eta, y, u, v, TREE)
}

den_sum <- function(y, u, v) {
    .Call('_NPT_den_sum', PACKAGE = 'NPT', y, u, v)
}

obj_fun <- function(coef, Z, y, u, v, tree) {
    .Call('_NPT_obj_fun', PACKAGE = 'NPT', coef, Z, y, u, v, tree)
}

rowvec_norm <- function(x, p) {
    .Call('_NPT_rowvec_norm', PACKAGE = 'NPT', x, p)
}

obj_try <- function(M, idx, ndim, p, fac, Z, y, u, v, tree) {
    .Call('_NPT_obj_try', PACKAGE = 'NPT', M, idx, ndim, p, fac, Z, y, u, v, tree)
}

obj_min <- function(coef, Z, y, u, v, tree, nrep, ftol, nfun_max) {
    .Call('_NPT_obj_min', PACKAGE = 'NPT', coef, Z, y, u, v, tree, nrep, ftol, nfun_max)
}

sum_I <- function(y, w) {
    .Call('_NPT_sum_I', PACKAGE = 'NPT', y, w)
}

